namespace: ernstov
may-22-ernst-blank:
  defines: runnable
  containers:
    may-22-ernst-blank:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: may-22-ernst-blank
      port: 8080
      protocol: tcp
